### ISSUE TITLE
Improve HTML meta tags

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#28]
Having decent meta tags will make the website easier to find, and will determine the rendering when links are shared. As this website is associated with campaigning, having the page optimized for search engines, and playing nicely with social media sharing is quite important.

*TODO*
- [x] Get metadata library inserted for indirection
- [x] Set default metadata
- [ ] Generate dynamic metadata based on content.

**Comment by nicorikken** [comment]
Also document the testing process, while doing this.

**Comment by nicorikken** [comment]
Tooling example: http://www.seocentro.com/tools/search-engines/metatag-analyzer.html
Use on live website. E.g. freedomvote.ch

**Comment by nicorikken** [comment]
Perhaps this can be set in the Django CMS management.

**Comment by nicorikken** [comment]
It seems that the package `django-meta` is a reasonably maintained library to ease metadata management. ([PyPi](https://pypi.python.org/pypi/django-meta), [GitHub](https://github.com/nephila/django-meta))

Alternatives exist:
- https://github.com/dreipol/meta-tagger
- https://pypi.python.org/pypi/django-seo/
- https://github.com/leveille/django-opengraph (too specific)

**Comment by nicorikken** [comment]
Actually, Django already provides some META options:

![screenshot from 2016-12-16 11-29-37](https://cloud.githubusercontent.com/assets/7458098/21259723/f72105a4-c382-11e6-8120-9496318d2fcc.png)

**Comment by nicorikken** [comment]
The Meata information can be useful for the custom pages, including the landing page, but it seems that would not cover all desired features, and would not work on the `Core` pages.

**Comment by nicorikken** [comment]
Looking further into it, it seems to concern indirection, where the template can dynamically be populated with meta tags, and this is included into the header via the `meta.html` include. This includes both static (settings.py) variables and page-specific meta tags.

**Comment by nicorikken** [comment]
I just got the `django-meta` package to work. Having the ability to differentiate meta information based on context would enable descriptions including the politician's name, or images of the politician's spider. Since we currently don't needs such context-aware meta, I welcome all tips on transferring the meta settings to `settings.py` My related commit: https://github.com/nicorikken/freedomvote/commit/3654d2f2a1b3089db91be43069d2fd1d6522f9ba

**Comment by nicorikken** [comment]
With my latest commit it seems to work, but due to all the changes my local database is having migrations issues I still have to resolve. Also I have to include the package in the requirements.txt. Expect a PR soon!

**Comment by andreabettich** [comment]
Resolved with the PR #53

**Comment by nicorikken** [comment]
Now also confirmed in Slack, which shows a preview based on a simple deploy:

![screen shot 2017-01-16 at 08 35 04](https://cloud.githubusercontent.com/assets/7458098/21974401/dd61604e-dbc6-11e6-902e-527d04054414.png)
